microservices:
  echo: "http://echo-kind-alligator.cfapps.io/api/echo"
  time: "http://time-unexpected-lion.cfapps.io/api/time"
  greeting: "http://greeting-bright-jackal.cfapps.io/api/greeting"
  whoami: "http://whoami-tired-fox.cfapps.io/api/whoami"
