microservices:
  time: "https://time-active-wombat.cfapps.io/api/time"
  greeting: "https://greeting-cheerful-pangolin.cfapps.io/api/greeting"
  whoami: "https://whoami-quick-dingo.cfapps.io/api/whoami"
